import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { unifont } from "@/assets/fonts";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Live Chat",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${unifont.className} ${geistMono.variable} antialiased`}
            >
                <div className="p-4 text-primary gap-2 items-center h-dvh flex flex-col">
                    {children}
                </div>
            </body>
        </html>
    );
}
